/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-container": "#fffbff",
        "surface-tint": "#0053db",
        "on-background": "#131b2e",
        "on-primary-container": "#eeefff",
        "on-surface": "#131b2e",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#0074a6",
        "secondary-fixed-dim": "#d2bbff",
        "on-tertiary-container": "#e4f2ff",
        "error-container": "#ffdad6",
        "surface": "#faf8ff",
        "background": "#faf8ff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-container": "#8a4cfc",
        "primary-container": "#2563eb",
        "secondary-fixed": "#eaddff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#283044",
        "on-primary-fixed": "#00174b",
        "outline-variant": "#c3c6d7",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-primary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "secondary": "#712ae2",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container": "#eaedff",
        "tertiary": "#005a82",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#dae2fd",
        "on-error-container": "#93000a",
        "outline": "#737686",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#004c6e",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "primary": "#004ac6",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "on-surface-variant": "#434655",
        "on-secondary-fixed": "#25005a"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "32px",
        "gutter": "16px",
        "base": "8px",
        "glass-padding": "20px",
        "container-padding": "24px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
